### ISSUE TITLE
UserAgent crashes on unsuccessful requests

### ISSUE THREAD

**Issue by pypt** [mediacloud/backend#733]
I've noticed quite a few crawler fetchers crashing when they were unable to fetch a page, e.g.

```
INFO crawler_fetcher.timer: Starting timer 'fetch'...
WARNING crawler_fetcher.engine: Error while fetching download 2734303588: HTTPSConnectionPool(host='jornalsemanario.com.br', port=443): Max retries exceeded with url: /feed/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)')))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/ssl_.py", line 347, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='jornalsemanario.com.br', port=443): Max retries exceeded with url: /feed/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)')))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/mediacloud/bin/crawler-fetcher.py", line 6, in <module>
    run_fetcher()
  File "/opt/mediacloud/src/crawler-fetcher/python/crawler_fetcher/engine.py", line 159, in run_fetcher
    raise ex
  File "/opt/mediacloud/src/crawler-fetcher/python/crawler_fetcher/engine.py", line 146, in run_fetcher
    _fetch_and_handle_download(db=db, download=download, handler=handler)
  File "/opt/mediacloud/src/crawler-fetcher/python/crawler_fetcher/engine.py", line 81, in _fetch_and_handle_download
    response = handler.fetch_download(db=db, download=download)
  File "/opt/mediacloud/src/crawler-fetcher/python/crawler_fetcher/handlers/default/fetch_mixin.py", line 57, in fetch_download
    response = ua.get_follow_http_html_redirects(url)
  File "/opt/mediacloud/src/common/python/mediawords/util/web/user_agent/__init__.py", line 398, in get_follow_http_html_redirects
    response = self.get(url)
  File "/opt/mediacloud/src/common/python/mediawords/util/web/user_agent/__init__.py", line 250, in get
    return self.request(request)
  File "/opt/mediacloud/src/common/python/mediawords/util/web/user_agent/__init__.py", line 777, in request
    raise ex
  File "/opt/mediacloud/src/common/python/mediawords/util/web/user_agent/__init__.py", line 775, in request
    user_agent_response = self.__execute_request(requests_prepared_request)
  File "/opt/mediacloud/src/common/python/mediawords/util/web/user_agent/__init__.py", line 687, in __execute_request
    stream=True,
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='jornalsemanario.com.br', port=443): Max retries exceeded with url: /feed/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)')))
```

`test_user_agent.py` is broken too.

I think this is due to this commit:

f4efdbd53813d6e07a14603642eef900c0df2533

I think this is rather critical as many parts of the code rely on the previous elaborate error handling in `UserAgent` which was pretty much gotten rid of in this commit. The commit message doesn't go into reasons either. So, in addition to crawler, we might want to look into what issues this could have caused in other workers as well and if some data needs reprocessing.

@hroberts could you take a look?

**Comment by pypt** [comment]
I reverted some BrandWatch-related commits to come up with an immediate fix for this issue, see referenced commits above.

**Comment by hroberts** [comment]
I removed the user_agent changes and then re-merged the brandwatch changes.

I also updated the database version back to 4757 to match the brandwatch db update.
